typography_spectrum: 0.587234
color:
  brandColors:
    - '#ffffff'
    - '#0d0817'
    - '#1d2a4f'
    - '#5c4544'
    - '#005352'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: juls.wtf
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/1d2a089c-50c6-4c07-a210-938edd5df154.jpg'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Juls.wtf
purpose: []
