name: juls.wtf
favicon: null
layout_spectrum: 0.8549301500897855
typography_spectrum: 0.65595
title: Juls.wtf
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0d0817'
    - '#1d2a4f'
    - '#5c4544'
    - '#005352'
  brandStrength: 0.6732550133019686
  lightness: 0.32247787388041615
  saturation: 0.5722033306956291
  rhythmicContrast: 0.7055640981998295
purpose: []
